package adcampaign

const (
	prefix = "act_%s"
)

var fields = []string{
	"auto_create_lookalike_new",
	"auto_create_lookalike_old",
	"bid_adjustments_spec_new",
	"bid_adjustments_spec_old",
	"bid_amount_new",
	"bid_amount_old",
	"bid_constraints_new",
	"bid_constraints_old",
	"bid_info_new",
	"bid_info_old",
	"bid_strategy_new",
	"bid_strategy_old",
	"bid_type_new",
	"bid_type_old",
	"billing_event_new",
	"billing_event_old",
	"brande_audience_id_new",
	"brande_audience_id_old",
	"budget_limit_new",
	"budget_limit_old",
	"created_time",
	"daily_impressions_new",
	"daily_impressions_old",
	"dco_mode_new",
	"dco_mode_old",
	"delivery_behavior_new",
	"delivery_behavior_old",
	"destination_type_new",
	"destination_type_old",
	"event_time",
	"event_type",
	"id",
	"invoicing_limit_new",
	"invoicing_limit_old",
	"min_spend_target_new",
	"min_spend_target_old",
	"name_new",
	"name_old",
	"optimization_goal_new",
	"optimization_goal_old",
	"pacing_type_new",
	"pacing_type_old",
	"run_status_new",
	"run_status_old",
	"schedule_new",
	"schedule_old",
	"spend_cap_new",
	"spend_cap_old",
	"start_time_new",
	"start_time_old",
	"stop_time_new",
	"stop_time_old",
	"targeting_expansion_new",
	"targeting_expansion_old",
	"updated_time_new",
	"updated_time_old",
}